language: haskell
ghc:
  - '8.4.1'

branches:
  only:
    - master
install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack install --local-bin-path $PWD/dist

after_success:
  - ghr --username tarektouati --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
