name: auth-service
version: 0.1.0.0
github: 'tarektouati/auth-service'
license: BSD3
author: 'Tarek Touati'
maintainer: 'tarektouati09@gmail.com'
copyright: '2019 Tarek Touati'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files- it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/tarektouati/auth-service#readme>

dependencies:
  - base >= 4.7 && < 5
  - servant-server
  - aeson
  - wai
  - warp
  - bytestring
  - jwt
  - uuid
  - time
  - text
  - containers
library:
  source-dirs: src

executables:
  auth-service-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - auth-service
tests:
  auth-service-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - auth-service
